### ISSUE TITLE
Stuck at Calculating...

### ISSUE THREAD

**Issue by kamalmemon** [hanzki/rsu-tax-calculator#1]
When I upload both CSVs and press the Calculate button, the app gets stuck at "Calculating.."

<img width="446" alt="image" src="https://user-images.githubusercontent.com/17003579/208468540-1e9a3fd2-6703-4e25-9f82-726a7c902fc8.png">

The error trace on console shows:

```
Uncaught Error: Could not match to lapse
    at Ie (index.ts:155:34)
    at Le (index.ts:112:34)
    at Fe (index.ts:273:22)
    at App.tsx:34:22
```

`App.tsx:34:22` is `setTaxReport(calculateTaxes(settings.individualHistory, settings.eacHistory, ecbConverter));`

**Comment by hanzki** [comment]
The error is related to the logic not being able to link the event of receiving shares in your individual history CSV to a RSU vesting event in the Equity Award Center history. Pay attention to the step 4. in the instructions. You might have accidentally exported only partial EAC history instead of all events.

Thanks for reporting this. I'll try to improve error handling in the future.

**Comment by kamalmemon** [comment]
Thanks, I think I missed the "press the Search button to update the list" point. I retried it and its still stuck at "Calculating.." but now I am getting a diff error

```
CreateForOfIteratorHelper.js:48  Uncaught Error: Couldn't match sell to a lot
    at l (index.ts:181:48)
    at index.ts:205:29
    at Fe (index.ts:276:43)
    at App.tsx:34:22
```
